name: Azure Databricks Terraform
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions: # This is the permissions level for the workflow
  id-token: write
  contents: read
  repository-projects: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARM_USE_OIDC: true # This is required for GitHub Actions to authenticate in Azure using Microsoft's Entra ID application(ARM_CLIENT_ID).
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          audience: "api://AzureADTokenExchange"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        id: tf-init
        env:
          TF_VAR_resource_group_name: ${{ secrets.TF_BACKEND_RG_NAME }}
          TF_VAR_storage_account_name: ${{ secrets.TF_BACKEND_STORAGE_ACCOUNT_NAME }}
          TF_VAR_container_name: ${{ secrets.TF_BACKEND_CONTAINER_NAME }}
          TF_VAR_key: ${{ secrets.TF_BACKEND_KEY }}
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false   